// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class End4 {
  final String appVersion;
  final String appType;
  final bool kIsDebug;

  const End4({
    required this.appVersion,
    required this.appType,
    required this.kIsDebug,
  });

  @override
  int get hashCode =>
      appVersion.hashCode ^ appType.hashCode ^ kIsDebug.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is End4 &&
          runtimeType == other.runtimeType &&
          appVersion == other.appVersion &&
          appType == other.appType &&
          kIsDebug == other.kIsDebug;
}
