// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/end4.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class End4 {
  final Client socket;
  final SocketOptions socketOptions;

  const End4({
    required this.socket,
    required this.socketOptions,
  });

  @override
  int get hashCode => socket.hashCode ^ socketOptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is End4 &&
          runtimeType == other.runtimeType &&
          socket == other.socket &&
          socketOptions == other.socketOptions;
}

class SocketOptions {
  final String appVersion;
  final String appType;
  final bool kIsDebug;
  final Fn onConnect;
  final Fn onConnecting;
  final Fn onDisconnect;
  final Fn onError;

  const SocketOptions({
    required this.appVersion,
    required this.appType,
    required this.kIsDebug,
    required this.onConnect,
    required this.onConnecting,
    required this.onDisconnect,
    required this.onError,
  });

  @override
  int get hashCode =>
      appVersion.hashCode ^
      appType.hashCode ^
      kIsDebug.hashCode ^
      onConnect.hashCode ^
      onConnecting.hashCode ^
      onDisconnect.hashCode ^
      onError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SocketOptions &&
          runtimeType == other.runtimeType &&
          appVersion == other.appVersion &&
          appType == other.appType &&
          kIsDebug == other.kIsDebug &&
          onConnect == other.onConnect &&
          onConnecting == other.onConnecting &&
          onDisconnect == other.onDisconnect &&
          onError == other.onError;
}
