name: vdlib
description: "A new Flutter project."

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  realm: ^1.7.0
  socket_io_client: ^2.0.3+1
  equatable: ^2.0.5
  fpdart: ^1.1.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
