// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../vdlib/vdlib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

End4 end4New({required SocketOptions socketOptions, dynamic hint}) =>
    RustLib.instance.api.end4New(socketOptions: socketOptions, hint: hint);

void end4Dispose({required End4 end4, dynamic hint}) =>
    RustLib.instance.api.end4Dispose(end4: end4, hint: hint);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<Client>>
@sealed
class Client extends RustOpaque {
  Client.dcoDecode(List<dynamic> wire) : super.dcoDecode(wire, _kStaticData);

  Client.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Client,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Client,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ClientPtr,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<fn ()>>
@sealed
class Fn extends RustOpaque {
  Fn.dcoDecode(List<dynamic> wire) : super.dcoDecode(wire, _kStaticData);

  Fn.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Fn,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Fn,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FnPtr,
  );
}
